version: '3'
services:

  neo4j:
    container_name: neo4je
    image: "neo4j:enterprise"
    ports:
      - "7474:7474"
      - "6477:6477"
      - "7687:7687"
    restart: always
    volumes:
      - "$PWD/neo4j/conf:/conf"
      - "neo4j_data:/data"
      - "$PWD/logs:/logs"
      - "$PWD/plugins:/plugins"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

networks:
  default:

volumes:
  neo4j_data:
